### DISCUSSION TITLE
Installation Help

### DISCUSSION THREAD

**Discussion by Bigbrian5** [eusonlito/GPS-Tracker#43] [Q&A] [answered]
When I try to run the docker compose image I get this PHP error:
![image](https://github.com/eusonlito/GPS-Tracker/assets/122059465/8a7d076c-0357-4c82-bdc8-156053139f11)

**Comment by eusonlito** [comment]
Do you build the instance with `./docker/build.sh` from project base path?

**Reply by Bigbrian5** [reply]
No I added this to an existing docker compose file and just did a docker compose up -d unless I need to run it in its own seperate docker compose file?

**Reply by Bigbrian5** [reply]
But I also plan on placing it behind traefik

**Reply by eusonlito** [reply]
The error is about relative files location. You should configure the Dockerfile files location with the correct relative project path.

**Reply by Bigbrian5** [reply]
Everything is in the correct location but yet it's complaining about these files being not found

**Reply by eusonlito** [reply]
I don't know how I can help you. Docker is failing because files can not be found :(

**Reply by Bigbrian5** [reply]
I manually copied those php.ini and crontab files into the correct directories and I will try to comment out those lines and see if it works

**Reply by Bigbrian5** [reply]
Based on my research and debugging it can't find the correct directory and is lost when I try to build this docker image

**Reply by Bigbrian5** [reply]
Will update when I find a solution!!

**Reply by eusonlito** [reply]
And if you run the docker installation using the scripts that are in the project itself does it work?

**Reply by Bigbrian5** [reply]
I still haven't tried running it using the scripts yet, my main reason why I haven't used your scripts even though they make it super easy to set up, it's that I want to place this behind, Traefik, and CrowdSec. So this isn't on your code not working. It's me being stubborn and wanting your docker app to live in my current stack! 🤠

**Reply by Bigbrian5** [reply]
But I suppose I can try to run your scripts and just add my traefik network as an external network! or I might be able to figure this out and document it here inorder to make it work with my current stack so others can do the same if they choose so!

**Reply by Bigbrian5** [reply, marked as answer]
Hazza! I have figured it out! I will write a little guide right here and right now! So the first 4 steps stay the same now I have your gps tracker app setup to be behind cloudflare with traefik using labels on the gpstracker-app. 
Docker Installation

1.  Clone the repository.
 git clone https://github.com/eusonlito/GPS-Tracker.git

2. [OPTIONAL] Copy file docker/.env.example to .env and configure your own settings which I added to my current .env file for my docker compose stack. The only thing that I changed was the APP_URL variable.
 cp docker/.env.example .env

3. [OPTIONAL] Copy file docker/docker-compose.yml.example to docker/docker-compose.yml and configure your own settings this is where I added the traefik v2 labels.
    cp docker/docker-compose.yml.example docker/docker-compose.yml
![image](https://github.com/eusonlito/GPS-Tracker/assets/122059465/c01e18ce-541d-4114-9483-c31487255a81)

4. Build docker images (will ask for the sudo password) this is CRUCIAL for retrieving the docker image needed to setup the app so run this command but after this if you are running in a seperate stack everything changes.
./docker/build.sh

5. Once this is complete then you can take that customized docker compose section and place it in you current stack here is mine.
![image](https://github.com/eusonlito/GPS-Tracker/assets/122059465/db53425c-1323-4687-9936-73ebde9ce593)
![image](https://github.com/eusonlito/GPS-Tracker/assets/122059465/fff34a55-4b91-43e5-92ad-fb6ad0aee0e8)
I commented out the condition tracker because I started each container by its, self from top to bottom.

6. I then ran the last line of the script ./docker/user.sh  in the command line 
 sudo docker exec -it gpstracker-app bash -c "cd /app && su -s /bin/bash -c 'php artisan user:create --email=$email --name=$name --password=$password --enabled --admin' www-data"
Where after every equals sign I replaced it with my values, Beware! the password variable doesn't like special characters!

7. Finally the last thing that I ran was the last line of the ./docker/timezone-geojson.sh in the command line
   sudo docker exec -it gpstracker-app bash -c "cd /app && su -s /bin/bash -c 'php -d memory_limit=-1 artisan timezone:geojson' www-data"
This takes about 5 minutes to finish and Vola you have Eusonlito's GPS-Tracker app running behind traefik and cloudflare!

**Reply by eusonlito** [reply]
Can you paste the full configuration as text instead images? Thanks!

**Comment by Bigbrian5** [comment]
Sure!
```yaml
 gpstracker-mysql:
    image: mysql:8.0
    container_name: gpstracker-mysql
    restart: unless-stopped
    volumes:
      - ./../storage/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=gpstracker
      - MYSQL_PASSWORD=$GTDB_PASSWORD
      - MYSQL_DATABASE=gpstracker
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    networks:
      - gpstracker-network
    healthcheck:
      test: mysqladmin ping -h localhost --password=root
      interval: 15s
      retries: 15

  gpstracker-redis:
    image: redis:7.0
    container_name: gpstracker-redis
    restart: unless-stopped
    networks:
      - gpstracker-network
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 15

  gpstracker-app:
    image: gpstracker-app:latest
    container_name: gpstracker-app
    restart: unless-stopped
    # depends_on:
    #   gpstracker-mysql:
    #     conditon: service_healthy
    #   gpstracker-redis:
    #     condition: service_healthy
    volumes:
      - $DOCKERDIR/appdata/gpstracker/
    ports:
      - "8091:80"
      - "8091:8091"
    networks:
      - gpstracker-network
      - t2_proxy
    tty: true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gpstracker-rtr.entrypoints=https"
      - "traefik.http.routers.gpstracker-rtr.rule=Host(`gpst.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.gpstracker-rtr.tls=true"
      - "traefik.http.routers.gpstracker-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.gpstracker-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.gpstracker-rtr.service=gpstracker-svc"
      - "traefik.http.services.gpstracker-svc.loadbalancer.server.port=80"
```
